### ISSUE TITLE
未初始化结构体成员被使用问题

### ISSUE THREAD

**Issue by tluio** [Tencent/TencentOS-tiny#150]
下边是一些由于使用kernel/core/tos_task.c中的tos_task_create函数造成的使用未初始化变量的问题，某些情况下会创建task失败。如果有不当的地方请见谅！

宏定义TOS_CFG_OBJECT_VERIFY_EN > 0u
因为在tos_task_create第100行的宏定义TOS_OBJ_TEST_RC中调用了knl_object_verify这个函数，这个函数使用了tos_task_create第一个参数task的成员task->knl_obj.type

1、components/connectivity/mqttclient/common/log/arch/tencentos-tiny/arch.c      
33行： salof_alloc为task申请的内存，没有初始化
35行： &task作为参数传递给tos_task_create
修复：这个好像没有salof_calloc，可以用tos_mmheap_calloc替换，但是破坏代码一致性了

2、components/connectivity/mqttclient/platform/TencentOS-tiny/platform_thread.c   
21行：platform_memory_alloc为thread申请内存，没有初始化
24行：&(thread->thread)作为参数传递给tos_task_create
修复：platform_memory_alloc换成platform_memory_calloc

3、osal/posix/pthread.c  
554行：tos_mmheap_alloc为stackaddr申请内存，没有初始化
564行：把stackaddr的地址赋给了the_ctl
585行：&the_ctl->ktask作为参数传递给tos_task_create了
修复：使用tos_mmheap_calloc

4、kernel/core/tos_task.c 
补充宏定义TOS_CFG_TASK_DYNAMIC_CREATE_EN > 0u
253行：tos_mmheap_alloc为the_task申请内存，没有初始化
265行： the_task作为参数传递给tos_task_create了
修复：使用tos_mmheap_calloc

对于以上问题的修复使用了calloc，但是calloc使用了memset，性能开销可能比较大，如果其它成员不存在未初始化使用的话，可以考虑单独为task->knl_obj.type赋值初始化。

**Comment by daishengdong** [comment]
感谢反馈，立刻修复！

**Comment by tluio** [comment]
> 感谢反馈，立刻修复！

不客气！

**Comment by daishengdong** [comment]
“因为在tos_task_create第100行的宏定义TOS_OBJ_TEST_RC中调用了knl_object_verify这个函数，这个函数使用了tos_task_create第一个参数task的成员task->knl_obj.type”

这个问题，因为task是用户传入的一片内存，这里没法确保用户对这片内存是否做了清零动作。实际上对于任意一个接口，都无法确保用户传入的内存到底内部是什么情况。

所以才设计了OBJ_VERIFY这一组宏，用魔术字校验的方式来校验用户是否传入正确参数。

如果用户确实传入了一个非法地址，且此地址上某一偏移处的内容恰好又是魔术字，就会刚好骗过这里的校验逻辑。但这种情况是不可避免的，同时也是低概率的。

而且对于task_create来说逻辑更为复位一些，因为此前有遇到有重复创建一个task的情况，就是说在task已经是一个合法的task情况下，再被创建一遍。因此这里又不能简单的对入参进行memset清零动作。

**Comment by tluio** [comment]
我感觉上面的一些函数是内核提供的函数，这里面申请的内存并不是用户控制的，应该可以初始化后再调用tos_task_create函数吧

**Comment by daishengdong** [comment]
task_create的入参task是用户传入的，不是内核维护的。

**Comment by tluio** [comment]
抱歉，我还是不太理解，上面列举的一些函数是tencentos-tiny源码里的，这些函数申请完内存之后，调用了task_create函数，把申请的内存传给task_create了，为什么不在这些源码里初始化后再调用task_create呢？如果用户直接调用task_create的话，确实是不可避免的。

**Comment by daishengdong** [comment]
你列举的情况确实是由内核维护的，我描述的是更为一般的情况。

**Comment by tluio** [comment]
嗯嗯，明白了，非常感谢您的回复！

**Comment by daishengdong** [comment]
客气，谢谢您的反馈。
