### ISSUE TITLE
Bug: 项目中, 有大量文件存在注释乱码的情况

### ISSUE THREAD

**Issue by Linjieqiang** [Tencent/TencentOS-tiny#17]
项目中, 有大量的文件存在乱码的情况, 例如: https://github.com/Tencent/TencentOS-tiny/blob/master/examples/tencent_cloud_sdk_data_template/light_data_template_sample.c

**Comment by daishengdong** [comment]
已修复，谢谢！

**Comment by Linjieqiang** [comment]
@daishengdong 其实还有很多噢 https://github.com/Tencent/TencentOS-tiny/blob/b34ce35f5ec751eca79eff0f98d8c81408dee6f4/components/connectivity/TencentCloud_SDK/source/include/qcloud_shadow.h#L104 请再次遍历下代码吧

**Comment by Supowang1989** [comment]
感谢，重新review了整个项目，大部分是因为之前有中文出现乱码，已经修复了一部分，类似问题会逐步迭代闭环，后期全部会要求采用英文注释，这个先close了。
