### ISSUE TITLE
TencentOS_tiny_EVB_MX_Plus与TencentOS_tiny_EVB_LX两个开发板的PM25文件出错了

### ISSUE THREAD

**Issue by DavidLin1577** [Tencent/TencentOS-tiny#181]
如下文件名是传感器解析，不过内容却是一个shell的实现代码，并不是PM25传感器的驱动代码，请知悉。

TencentOS-tiny/board/TencentOS_tiny_EVB_LX/BSP/Hardware/PM25/sensor_parser.h
TencentOS-tiny/board/TencentOS_tiny_EVB_LX/BSP/Hardware/PM25/sensor_parser.c

TencentOS-tiny/board/TencentOS_tiny_EVB_MX_Plus/BSP/Hardware/PM25/sensor_parser.c
TencentOS-tiny/board/TencentOS_tiny_EVB_MX_Plus/BSP/Hardware/PM25/sensor_parser.h

**Comment by Supowang1989** [comment]
这个是用了shell的串口收数据机制来处理传感器接收数据的逻辑，只是特定板子的bsp代码哈
