### ISSUE TITLE
一些期盼和设想

### ISSUE THREAD

**Issue by j-w-huang** [Tencent/TencentOS-tiny#19]
最近国内各大厂商都在做物联网操作系统的东西，我都十分关注。从最早的华为LiteOS，当下火热的RT-Thread，还有稍有亮色的AliOS-things，小厂如SylixOS，都江堰OS之类的林林总总.....，感叹我大汉民族正在文艺复兴的同时，又不免心生悲凉。。。
对比老牌的uC-OS\Contiki\freeRTOS，我们的特色在哪里？RT-Thread,AliOS-things，还是给了点骄傲，先不论内核的先进性，RT-Thread,AliOS-things易用性还算有起色，RT-Thread的仿Linux编译模式，AliOS-things的SCons再次封装包裹，都给开发者带来了不一样的体验，但用起来还是那么的笨拙。JAVA、Node程序员永远不知道嵌入式程序员的苦，嵌入式程序员永远不知道纯软程序员的爽。
不想长篇大论了，我感觉STM32CubeMx+freeRTOS正走在我梦想的道路上，但生态还局限在STM系列内。Arm MBedOS在Porting过程中还算及格。至于RT-Thread,想法挺好，但用起来真的想吐槽。
我想说的是什么？其实很简单。就是能不能把你们的系统内核、组件的颗粒度做小，配置方便些，组件化编程。做个包管理器，做个脚手架配置。真的难吗？另外，我真的不想用Keil了，最好把C也放到板凳上，用Rust好吗？
还有，清华本科的学生一样都能做的(https://github.com/rcore-os/rCore)东西，作为大厂，你们的颜面何在？

**Comment by alexddhuang** [comment]
@j-w-huang 连链接的 markdown 语法都写不好，你颜面何在？

**Comment by j-w-huang** [comment]
@alexddhuang 我是贱民，不在乎颜面。批评是为了你们做的更好而已。

**Comment by murphyzhao** [comment]
有不爽，有意见，这是好事，可以促使我们改变现状。但，重点是改变，改变不全是别人的事情，如果你有想法、有能力、有梦想，那请怀着敬畏与尊重附着到执行力上，加入进来一起去探索、、创造、改变！

**Comment by balanceTWK** [comment]
放心好了，现在国内的物联网操作系统遍地开花，竞争激烈。为了能够吸引开发者使用，易用性 门槛 这些。。。各个厂家都不会忽视的，谁忽视谁就会被淘汰。

另外说一句：国内开源操作系统的生态想要做好，需要的是使用者也参与到操作系统的开发当中来（贡献软件包组件或者优化内核代码逻辑），如果使用者只是一味着获取，不去深入学习源码，不去做贡献，那么开源的意义何在？

**Comment by j-w-huang** [comment]
情怀是一回事，能力是另外一回事。不论这些。做与不做，要做什么，怎么做，是根本。跟风弄浪，也要有姿态的。小生不才，吐吐槽而已。至于开源做事，要的是时间。等我规划好了，一定搞他个惊世骇俗！

**Comment by tommybreak** [comment]
> 放心好了，现在国内的物联网操作系统遍地开花，竞争激烈。为了能够吸引开发者使用，易用性 门槛 这些。。。各个厂家都不会忽视的，谁忽视谁就会被淘汰。
> 
> 另外说一句：国内开源操作系统的生态想要做好，需要的是使用者也参与到操作系统的开发当中来（贡献软件包组件或者优化内核代码逻辑），如果使用者只是一味着 获取和提要求，不去深入学习源码，不去做贡献，那么开源的意义何在？

十**### 万分赞同！！！**
说得好！！！

**Comment by dcxajichu** [comment]
技术不等于商业，更不等于商用。这个可能得等你再成熟些才能有体会。

**Comment by daishengdong** [comment]
谢谢关注，开发人员全是清华，没有kpi压力，没有商用压力，没有推广压力，这相对商业公司就已经占据了绝对的优势了。您反映的问题我们都会改进，项目刚起步，请多包涵。

**Comment by GamebabyRockSun** [comment]
有意见虚心接受，为什么好好的技术讨论变成吐槽和谩骂？这就是大汉族程序员的样子？大家都淡定点，才起步有些问题难免的，罗马不是一天修成的，不积跬步更无以至千里，多提建设性意见，多互相帮助，共同出力，不愿出力的也请报个路过的心态。

**Comment by GamebabyRockSun** [comment]
等我过段时间清闲了，好好看看你们的项目，看看能不能帮上什么忙，之前也研究过操作系统内核，但很久了，也淡忘了，全当是复习，更是为了那直径难以释怀的情怀。

**Comment by LingaoM** [comment]
嵌入式领域，国内主要已应用为主，而在国际规范制定（WIFI 蓝牙）、高端芯片制造（内核、处理器）、工业软件（开发工具、开发软件）、操作系统（Android、微软）等基础性研究领域大多是有心无力，个人认为出现这种缺芯少魂的窘境，与我国经济发展阶段的原因密不可分。应当尊重客观规律，少一点抱怨与责备，同时也需有洞察之力，发现我国现阶段的短板弱板，敢于打破陈规，做出一个特色鲜明的Things。
