### ISSUE TITLE
为啥我们的内存分配模块这么像

### ISSUE THREAD

**Issue by PowerfulCat** [Tencent/TencentOS-tiny#2]
https://github.com/Better-Idea/Mix-C/blob/master/%E5%9F%BA%E6%9C%AC%E5%AE%9A%E4%B9%89/%E8%BF%B7%E4%BD%A0.cpp
都是通过最高置位位（类似intel的bsf指令 arm的clz指令）判断最接近所需内存大小的可用块，然后通过链表数组保存空闲块（我的是一维，你们的是二维）

**Comment by Supowang1989** [comment]
是的，编程思想是差不多的
