### ISSUE TITLE
AT组件使用mutex时 导致硬件错误

### ISSUE THREAD

**Issue by zque** [Tencent/TencentOS-tiny#226]
![5LMT26LDXAT@XUBUDV2~(M](https://user-images.githubusercontent.com/18100043/92078290-979ffd00-edf0-11ea-8876-9a808e59173b.png)

**Comment by Mculover666** [comment]
描述可以具体一点吗？可以把代码也贴上来~

**Comment by zque** [comment]
https://github.com/zque/tencentOS

**Comment by zque** [comment]
水平有限，不知道具体哪里出问题了。就把项目打包传上来了

**Comment by zque** [comment]
之前的文件有加密， 我重新上传了

**Comment by zque** [comment]
![CGC%GAG`83E5P8$20O 5M{C](https://user-images.githubusercontent.com/18100043/92302809-97932f00-efa1-11ea-9eda-901828835bba.png) 我打断点看了下， 程序跑到 tos_mutex_pend_timed 函数里 读取 k_curr_task   读取到的是0 才导致程序跑飞的

**Comment by zque** [comment]
main 函数里调用的是 application_entry（） 进程没跑起来

改为  osThreadCreate(osThread(application_entry), NULL); 就好了
