### ISSUE TITLE
执行make_mac_stm32cubeide_code.sh会删除同目录文件

### ISSUE THREAD

**Issue by illusionlee** [Tencent/TencentOS-tiny#23]
这个脚本文件在苹果系统执行时，会将同目录的其他文件夹删除，并且不会有任何警告！作为一名刚上手的初学者，这个地方坑了我好几次，删除了我好几个重要文件！对开发者体验很不友好，代码注释较少，没有找到使用文档。
我提交了PR单独修复此文件，请审核，谢谢。

**Comment by zhaoyanbai** [comment]
这个我当初写的时候是放到父目录去执行，当初在内网的时候，我把注释写在这个文档里了

https://github.com/Tencent/TencentOS-tiny/blob/master/doc/TencentOS-tiny-porting(MacOS_STM32CubeIDE).md

![image](https://user-images.githubusercontent.com/7145333/65824323-ac4b4b00-e299-11e9-962c-4d621c323c1d.png)

可能是合代码的时候出了偏差，开源之前可能忘合了某些提交。。。

抱歉~

**Comment by acevest** [comment]
这个我当初写的时候是放到父目录去执行，当初在内网的时候，我把注释写在这个文档里了

https://github.com/Tencent/TencentOS-tiny/blob/master/doc/TencentOS-tiny-porting(MacOS_STM32CubeIDE).md

![image](https://user-images.githubusercontent.com/7140471/65824353-21b71b80-e29a-11e9-84d4-319feb2f32b4.png)


可能是合代码的时候出了偏差，开源之前可能忘合了某些提交。。。

抱歉~

**Comment by acevest** [comment]
#22

**Comment by illusionlee** [comment]
我看了你这个说明，发现我确实是按照你这个步骤做的。
不过，我仅执行的 make_mac_stm32cubeide_code.sh 这个部分。
经过分析，我明白了原因：
官方的库名称是：TencentOS-tiny
你shell中名称是：TencentOS_tiny
不同的是中间的连接符，一个是"-",一个是"_"
OMG...

**Comment by acevest** [comment]
内网是 "_"，外网是"-"

。。。。。。。

**Comment by Supowang1989** [comment]
感谢反馈，已经合入并修复。
