### ISSUE TITLE
关于tos_task_destroy_dyn文档说明有误

### ISSUE THREAD

**Issue by xnvi** [Tencent/TencentOS-tiny#239]
`__STATIC__ k_err_t task_destroy_dyn(k_task_t *task)，`
该函数声明如上，文档里的函数名写错了，没有tos_前缀。函数声明为static，并不是一个对外开放的接口，实际销毁动态创建的任务还是调用tos_task_destroy()，然后在tos_task_destroy()内部调用task_destroy_dyn()
文档路径 /doc/05.SDK_Manual.md

**Comment by Supowang1989** [comment]
已添加说明，谢谢指出
