### ISSUE TITLE
No tos_hal_uart_read() function in /net/at/src/tos_at.c

### ISSUE THREAD

**Issue by tommytim0515** [Tencent/TencentOS-tiny#241]
According to my understanding, there should be one task in tos_at.c which can keep receiving data from the UART port and store the data in recv_cache of AT_AGENT. However, I cannot find that tos_hal_uart_read() implemented in tos_at.c and I am also facing problems letting my Wi-Fi module (ESP8266) function properly.

**Comment by Supowang1989** [comment]
Thanks for your question.  We use tos_at_uart_input_byte() to read char data in uart interrupt，this function will push data into fifo. So you can do it like this  https://github.com/Tencent/TencentOS-tiny/blob/master/board/TencentOS_tiny_EVB_MX_Plus/BSP/Src/stm32l4xx_it_module.c
#include "tos_at.h"
...

/* USER CODE BEGIN 1 */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    extern uint8_t data;
    if (huart->Instance == LPUART1) {
        HAL_UART_Receive_IT(&hlpuart1, &data, 1);
        tos_at_uart_input_byte(data);
    }
}

**Comment by tommytim0515** [comment]
Thank you so much for your guidance! I have modified my program and it can work properly now.
By the way, I noticed that if I use the configuration in the example above, I have to call HAL_UART_Receive_IT() once after MX_USARTx_UART_Init(), perhaps in tos_hal_uart_init() in [/kernel/hal/tos_hal_uart.c](/kernel/hal/tos_hal_uart.c). (I am using stm32f103 MCU)

**Comment by Supowang1989** [comment]
Yes we must call  HAL_UART_Receive_IT()  once after MX_USARTx_UART_Init()， This is determined by the use of the STM32 HAL library. We will not merge your PR, because we will update the code of the AT framework in the next month to improve the overall performance.

**Comment by tommytim0515** [comment]
Well noticed with thanks~
