### ISSUE TITLE
在nrf52840上开发TencentOS 

### ISSUE THREAD

**Issue by fengjikui** [Tencent/TencentOS-tiny#272]
您好，在plateform和board中看到有nrf52840的目录，请问是可以直接在nrf52840上运行example下的例程吗？

**Comment by Supowang1989** [comment]
https://github.com/Tencent/TencentOS-tiny/tree/master/board/Nordic_NRF52840/KEIL 这个目录下的可以运行，example下面的并不一定都适用于NRF52840
