### ISSUE TITLE
想请问一下，“任务栈的吃水深度”是什么意思？

### ISSUE THREAD

**Issue by lbcqc** [Tencent/TencentOS-tiny#45]
### tos_task_stack_draught_depth

```c
k_err_t tos_task_stack_draught_depth(k_task_t *task, int *depth);
```

- **功能描述**

  获取一个任务栈的最大吃水深度。

- **参数解释**

  | **IN/OUT** | **参数名** | **描述**         |
  | ---------- | ---------- | ---------------- |
  | [in]       | task       | 任务结构体描述符 |
  | [out]      | depth      | 任务栈的吃水深度 |

- **返回值**

  K_ERR_NONE 任务栈状态正常。

  K_ERR_TASK_STK_OVERFLOW 任务栈溢出。

**Comment by daishengdong** [comment]
就是任务栈被用到的最大深度
