### ISSUE TITLE
GCC 编译警告 & README链接未更新

### ISSUE THREAD

**Issue by JassyL** [Tencent/TencentOS-tiny#63]
![image](https://user-images.githubusercontent.com/16059514/69220540-3c2db700-0bb0-11ea-843d-cbc3cfd60503.png)
按照移植教程，警告如图所示`state_str`未初始化，初始化为`NULL`后警告消失

另外`README.md`文件的部分链接地址未更新(开发指南等)，与`./doc/`目录下文件名不匹配

**Comment by Supowang1989** [comment]
README.md doc链接问题已经处理，感谢反馈。 warnning我们看下，谢谢
