### ISSUE TITLE
你好，后续会支持ubuntu 或者windows下运行tos吗？

### ISSUE THREAD

**Issue by zjd1988** [Tencent/TencentOS-tiny#66]

**Comment by Supowang1989** [comment]
https://github.com/Tencent/TencentOS-tiny/tree/master/board/Linux_Posix/hello_world 
您好，当前支持在linux上运行TencentOS tiny

**Comment by zjd1988** [comment]
嗯嗯，谢谢，看到了，那windows后续会有支持的计划吗？

**Comment by huhansome** [comment]
阿里云服务器，限时秒杀价低至102/年
http://weibo.ws/zZNbxG
阿里云企业级服务器1折限时特惠
http://weibo.ws/SIyDRE
阿里云建站 速成美站 - 千套模板，价格低至500元
http://weibo.ws/yVQAYW
