### ISSUE TITLE
树莓派可以刷这个系统么？

### ISSUE THREAD

**Issue by lhggame** [Tencent/TencentOS-tiny#8]
已知Respberry Pi3 可以刷 FreeRTOS

**Comment by lhggame** [comment]
FYI：
https://github.com/Forty-Tw0/RaspberryPi-FreeRTOS

**Comment by balanceTWK** [comment]
已知 Raspberry Pi 2B 可以刷 RT-Thread

https://github.com/RT-Thread/rt-thread/tree/master/bsp/raspi2 （逃。。。。。

**Comment by Supowang1989** [comment]
TencentOS tiny目前支持的IP核主要是ARM M核和risc-v，未来有规划更多IP核支持，包括ARM A核支持，后期也会在树莓派上做porting工作，敬请期待，谢谢！
