### ISSUE TITLE
devices/rhf76_lora/RHF76.c的函数rhf76_incoming_data_process数组处理错误

### ISSUE THREAD

**Issue by DavidLin1577** [Tencent/TencentOS-tiny#80]
1.定义__STATIC__ char incoming_data_buffer[128];，数组长度是128，但是在函数内部 memset(incoming_data_buffer, 0x00, 512));，此时清零的长度是512，这会导致内存泄漏
应该修复成memset(incoming_data_buffer, 0x00, 128));，但为了避免类似错误，使用
 memset(incoming_data_buffer, 0x00, sizeof(incoming_data_buffer));
2.__STATIC__ char incoming_data_buffer[128];  but in function  memset(incoming_data_buffer, 0x00, 512); define is 128, memset is 512.
3. so we fixed this replace with 'sizeof(incoming_data_buffer)', just like this 'memset(incoming_data_buffer, 0x00, sizeof(incoming_data_buffer));'

**Comment by daishengdong** [comment]
非常感谢，这里我们马上修复。同时后续模组抽象层接口会进行一些重构，将数据接收buffer作为模组初始化的入参，让用户指定接收的buffer及大小。

**Comment by daishengdong** [comment]
实在不好意思，没看到您的PR，我自己提交了修改。

**Comment by DavidLin1577** [comment]
没事^-^
