### ISSUE TITLE
qcloud_shadow_glue.c函数注释乱码问题

### ISSUE THREAD

**Issue by DavidLin1577** [Tencent/TencentOS-tiny#84]
该文件多个函数注释为乱码，请原作者维护，请知悉。

**Comment by daishengdong** [comment]
谢谢，后面处理一下。

**提醒：**
这套qcloud打头的TencentCloud_SDK连腾讯云组件是我们实现的，接口、代码的层次相对腾讯云实现的c-sdk来说清晰一些。但是数据模板服务器端的接入协议，后来腾讯云进行了一次变动，导致我们实现的这一套sdk在数据模板的功能上会有一些问题。实际上，TencentCloud_SDK这套实现现在不推荐使用，后续也许会针对腾讯云后端的新协议进行重新实现，但目前来说推荐的是腾讯云实现的c-sdk，也就是qcloud-iot-explorer-sdk和qcloud-iot-hub-sdk-3.1.2，相关的sample也是推荐这一套sdk实现的。

可以参考我的这一次commit：
https://github.com/Tencent/TencentOS-tiny/commit/943db74fc7a23109b6ec9bcf34d178aea5f7cc22
