### ISSUE TITLE
这个基础部分和ucos很像，网络部分能和腾讯云配合很好

### ISSUE THREAD

**Issue by mcwhy** [Tencent/TencentOS-tiny#9]
这个基础部分和ucos很像，网络部分能和腾讯云配合很好，看看能不能和微信小程序结合一下。下午申请个内测。

**Comment by Supowang1989** [comment]
基础内核是自研的，要说像，大部分RTOS的思想都是类似的。网络部分我们提供SDK，支持腾讯云IoT平台接入，tools目录下已经有小程序demo了，欢迎体验！
